// IMPORTS
import { type NextPage } from "next";
// import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

// COMPONENTS
import Head from "next/head";
// import Alert from "../components/Alert";
import Hero from "../components/Hero";
import Solutions from "../components/Solutions";
import CardStack from "../components/CardStack";
import Partners from "../components/Partners";
import HeroCards from "../components/HeroCards";
import FormSection from "../components/FormSection";
import TestimonialFeed from "../components/TestimonialFeed";
import Industries from "../components/Industries";
import Products from "../components/Products";
import Alert from "../components/Alert";

const Home: NextPage = (props) => {
  const trpcMessage = trpc.api.alert.useQuery({
    title: "Alert:",
    msg: "Hello World, from tRPC.",
  });
  return (
    <>
      <Head>
        <title>Rugged Development</title>
        <meta name="description" content="Generated by T3D" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Alert
        title={trpcMessage.data?.title ?? "loading..."}
        msg={trpcMessage.data?.msg}
      />
      <Hero
        title="Rugged Development"
        description="We supply, deploy, and support technology designed to for the most demanding environments on earth."
      />

      <div className="bg-neutral-900">
        <HeroCards />
        <Solutions />
        <CardStack />
        <Industries />
        <Products />
        <Partners />
        <TestimonialFeed />
        <FormSection />
      </div>
    </>
  );
};
export default Home;
